version: "3.8"
services:
  db:
    image: postgres:15
    container_name: hotel_pg
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: hotel_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: hotel_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@hotel.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - db

  app:
    build: .
    container_name: hotel_api
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "3000:3000"

volumes:
  pgdata:
